### ISSUE TITLE
question about the code of 'xjacm array structure' in usermat3d.f .

### ISSUE THREAD

**Issue by Budong-zhangliang** [Andrey-Fog/ANSYS-USERMAT-CMSG#4]
In the source code (line 299- line 347) of usermat3d.f, the Jacobian matrix 'xjacm' line and column are mixed. [xjacm](3*3)=matmul(deriv(3*8), coord(8*3)). 

For example, xjacm(1,2) should be xjacm(2,1)
         xjacm(1,2)= deriv(2,1)*SVAR(1,1)+deriv(2,2)*SVAR(2,1)
     1 +deriv(2,3)*SVAR(3,1)+deriv(2,4)*SVAR(4,1) 
     2 +deriv(2,5)*SVAR(5,1)+deriv(2,6)*SVAR(6,1) 
     3 +deriv(2,7)*SVAR(7,1)+deriv(2,8)*SVAR(8,1) 

If possible, please check it. Many thanks.

**Comment by Andrey-Fog** [comment]
Yes, in this part line and column are mixed. I'm think source code is correct for my structure of arrays. I will check it for sure later.

**Comment by Andrey-Fog** [comment]
Fixed. Thank you.

**Comment by Budong-zhangliang** [comment]
Many thanks!However,xjacm(1,2) and xjacm(2,1) are fixed, while xjacm(1,3) and xjacm(3,1), xjacm(2,3) and xjacm(3,2) are not fixed.
